### ISSUE TITLE
What is the current status of this project?

### ISSUE THREAD

**Issue by jarmanso7** [mwpenny/gbplay#23]
First of all I would like to appreciate all the work you have done so far. Thank you for starting this project, the vision of enabling GB playing over the internet is just mindblowing.

I would like to know if the project is still on going, as the last entry in the blog dates back to 2022? If so, is there any way I can contribute? I don't know anything about hardware but maybe I can help with the server, or whatever.

In any case, thanks again!

looking forward to hearing from you guys.

**Comment by mwpenny** [comment]
Hi there, thanks for the interest!

You're right that this project has been somewhat dormant. I do plan to return to it. However, my current focus is [portal64-still-alive](https://github.com/mwpenny/portal64-still-alive). I'm in research mode right now, which involves a lot of focused effort. Once I've built a good foundation, made more progress, and individual changes are easier, I'll have more time to come back to GBPlay - which I'm still very interested in.

I actually have another blog post mostly complete from last year about how we got the ESP32-based Wi-Fi setup working. It's just missing some details about a custom board we made for voltage shifting and some issues we had debugging that.

The project currently works wirelessly over the internet for small test cases like Tetris and Pokemon trades, although it's a bit rough. From here, the plan is to build out the different layers of the stack so that we have a solid vertical slice which can be tested and improved together rather than focusing on a single component. After everything works, we will shift attention to more granular areas like supporting more games, easier wireless adapter setup, etc.

The next missing piece to implement is a web interface to select/host game lobbies, choose the current game and its settings, etc. The first step is a mockup/skeleton that is non functional, then the server can be hooked up to it (which will likely require additions to the wireless adapter firmware). I also had some performance improvements in mind like packetization of large buffers that don't need a response for every byte.

So if you're interested in contributing, some web interface experimentation would be quite helpful - even if it isn't used until some time in the future. Just know that, while I can review what you've done and give feedback, I won't have time to really work on this for a while.

All the best.

**Comment by jarmanso7** [comment]
Thank you very much for taking your time to respond quickly. I understand this kind of projects may extend for years because everyone has a life and work to do, but nonetheless I am very glad to hear that you still have the intention to resume it at some point. I will take a look and see if I can come up with a web interface in my spare time.

Best regards

**Comment by jarmanso7** [comment]
Thank you very much for taking your time to respond quickly. I understand this kind of projects may extend for years because everyone has a life and work to do, but nonetheless I am very glad to hear that you still have the intention to resume it at some point. I will take a look and see if I can come up with a web interface in my spare time.

Best regards
