### ISSUE TITLE
Link Cable -> Arduino Uno pin diagram

### ISSUE THREAD

**Issue by spjoes** [mwpenny/gbplay#26]
Hello! Is there any chance you could add a pin setup for connecting the link cable breakout board to the arduino UNO? It would be very helpful for others trying to help with this project or those who would like to test it out.

EDIT: I actually figured it out. (My initial testing didnt work because I forgot to install the .ino program onto my arduino)
For anyone else coming along or anyone who wants to make a pin diagram:

The link cable breakout board has:
VDD
SO
SI
SD
SC
GND

Connecting these to the arduino (assuming you are following along with the gbplay project so far):
VDD -> Empty
SO -> Pin 3 (DIGITAL PWM side)
SI -> Pin 4 (DIGITAL PWM side)
SD -> Empty
SC -> Pin 2 (DIGITAL PWM side)
GND -> Any GND pin I believe. I have mine in the GND pin on the DIGITAL PWM side of the Arduino (and the gbplay blog does too)

**Comment by mwpenny** [comment]
Glad you got it working. In addition to the higher-level explanations in the blog, the pins are defined in [gb_to_serial.ino](https://github.com/mwpenny/gbplay/blob/e00784829d8468e97dd3d17a9dfe22e29cbf646e/arduino/gb_to_serial/gb_to_serial.ino#L2,3,4).

Please close this issue if your issue is resolved.
